# Generated by Django 4.1.7 on 2023-03-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_finish", models.BooleanField(default=False)),
                ("winner", models.CharField(blank=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="GamePlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_points", models.IntegerField(default=0)),
                ("city_points", models.IntegerField(default=0)),
                ("monastery_points", models.IntegerField(default=0)),
                ("farm_points", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameplay",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
