# Generated by Django 4.1.7 on 2023-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(related_name="game", to="players.player"),
        ),
    ]
